// EvalKit — all processing is on-device. No data leaves the device.
//
// JudgeRunner.swift
// EvalKitJudge/Protocols
//
// Protocol for running a judge LLM evaluation on free-form generated text.

import Foundation

/// A runner that uses a judge LLM to evaluate the quality of free-form generated output.
///
/// **EvaluationRunner vs JudgeRunner — when to use which:**
///
/// - Use `EvaluationRunner` (EvalKit core) when there is one correct answer and you can
///   write `predicted == expected`. The result is always right or wrong.
///   *Example: text classification, topic retrieval.*
///
/// - Use `JudgeRunner` when there is no single correct answer and any well-written
///   response may be acceptable. The judge LLM scores the model's output quality.
///   *Example: greeting generation, summarisation, response tone.*
///
/// **Rule of thumb:** If you can write `predicted == expected`, use `EvaluationRunner`.
/// If any well-written answer is acceptable, use `JudgeRunner`.
///
/// **Two scoring patterns within JudgeRunner:**
///
/// - **Holistic (1–5)**: The judge reads input + output and returns a single impression
///   score (1–5) with reasoning. Used for fluency, tone, safety, coherence.
///
/// - **Item-by-item (0/1 per fact)**: The judge receives input + output + a list of key
///   facts and scores each fact independently (1 = present, 0 = missing). The final score
///   is a ratio: `sum(scores) / count(facts)`. Used for recall and groundedness.
public protocol JudgeRunner: Sendable {

    /// The type representing a complete judge evaluation for one test case.
    associatedtype Score: Sendable

    /// Evaluate a single generated output and return a judge score.
    ///
    /// - Parameters:
    ///   - caseId: Stable identifier for this test case.
    ///   - input: The original prompt or context given to the model.
    ///   - output: The free-form text generated by the model under evaluation.
    /// - Returns: A `Score` covering all configured dimensions for this case.
    func evaluate(caseId: String, input: String, output: String) async -> Score
}
