// EvalKit — all processing is on-device. No data leaves the device.
//
// RuleViolation.swift
// EvalKitRules
//
// Represents a single rule violation recorded during a rules evaluation.

import Foundation

/// A single rule violation recorded when a model output fails an `EvaluationRule`.
///
/// ## Purpose
///
/// `RuleViolation` is produced by an `EvaluationRule` when its `evaluate(output:context:)`
/// method returns `false`. It captures the rule that fired, a human-readable explanation of
/// why the output failed, and the raw output that was evaluated. You receive violations as
/// part of `RulesResult.violations`.
///
/// ## When to use
///
/// Inspect `RuleViolation` values when analysing report failures — e.g. to find all cases
/// where a language rule fired or to print a summary of violation messages per rule.
public struct RuleViolation: Sendable {

    // MARK: - Properties

    /// The name of the rule that was violated.
    ///
    /// Corresponds to `EvaluationRule.name` of the failing rule. Use this to group violations
    /// by rule across the batch (e.g. count how many cases violated the language rule vs the
    /// word limit rule).
    public let ruleName: String

    /// Human-readable message explaining why the output violated this rule.
    ///
    /// Generated by the rule's `failureDescription(for:context:)` method. Examples:
    /// - `"Output exceeds maximum of 100 words (was 143)."`
    /// - `"Expected language 'fr', but detected 'en'."`
    /// - `"Output contains item 'other' that is not in the allowed list."`
    public let failureMessage: String

    /// The raw model output string that triggered this violation.
    ///
    /// Storing the output in the violation allows you to reproduce and debug a failure
    /// without re-running the model. May be the full output even if only part of it
    /// caused the violation.
    public let output: String

    // MARK: - Init

    /// Create a rule violation record.
    ///
    /// - Parameters:
    ///   - ruleName: The name of the violated rule (from `EvaluationRule.name`).
    ///   - failureMessage: Human-readable explanation of the failure.
    ///   - output: The raw model output that failed the rule.
    public init(ruleName: String, failureMessage: String, output: String) {
        self.ruleName = ruleName
        self.failureMessage = failureMessage
        self.output = output
    }
}
